name:                changelog2json
version:             0.1.0.0
github:              "cloudorz/changelog2json"
license:             BSD3
author:              "Cloud"
maintainer:          "cloudcry@gmail.com"
copyright:           "@cloud"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cloudorz/changelog2json#readme>

dependencies:
- base >= 4.7 && < 5
- time
- megaparsec
- aeson
- parser-combinators
- text
- bytestring
- aeson-pretty

library:
  source-dirs: src

executables:
  changelog2json:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - changelog2json

tests:
  changelog2json-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - changelog2json
    - hspec
